let places: string[]= ["Paris","London","Japan","Malaysia","China"];
console.log("Original order:",places);
console.log("Alphabetical order:", [...places].sort());
console.log("Original order:",places);
console.log("Reverse Alphabetical order:",[...places].sort().reverse());
console.log("Original order:",places);
places.reverse();
console.log("Reversed order:",places);
places.reverse();
console.log("Original order:",places);
places.sort();
console.log("Alphabetical order:",places);
places.reverse();
console.log("Reversed alphabetical order:",places);
